services:
  web:
    image: odoo:19
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
    depends_on:
      - db
    ports:
      - "8069:8069"
  db:
    image: postgres:15
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo360
      - POSTGRES_USER=odoo360
volumes:
  odoo-web-data:
  odoo-db-data:
